version: '3.7'
services:
  db:
    image: mongo:3.4
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  back:
    build: ./backend/
    environment: 
      - DATABASE_HOST: db
      - DATABASE_PORT: 27017
      - DATABASE_NAME: wheretopark
      - DATABASE_USERNAME: root
      - DATABASE_PASSWORD: root
    ports:
      - '3000:3000'
  front:
    build: ./frontend/
    environment:
      - BACKEND_URL=http://back:3000
    ports:
      - '80:80'